[package]
name = "kelk-derive"
version = "0.1.0"
edition = "2018"
authors = ["Zarb development team <admin@zarb.network>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.6"
