[package]
name = "accessor"
version = "0.0.1"
edition = "2018"
authors = ["Zarb development team <admin@zarb.network>"]

[dependencies]
kelk = { path = "../../kelk" }

[lib]
name = "accessor"
path = "lib.rs"
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
