on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Testing and linting (wasm32)

jobs:
  wasm-32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup toolchain install nightly --component clippy
          rustup toolchain install nightly --target wasm32-unknown-unknown
          # installing wasm-pack (https://rustwasm.github.io/wasm-pack/installer/)
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Testing env crate (wasm32)
        run: |
          cd crates/env
          rustup run nightly $HOME/.cargo/bin/wasm-pack test --node


      - name: Clippy check (wasm-32)
        run: cargo +nightly clippy --target wasm32-unknown-unknown --all-features -- -D warnings
