on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Coverage and linting (x86-64)

jobs:
  x84-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup toolchain install nightly --component llvm-tools-preview rustfmt clippy

      - name: Install cargo-llvm-cov
        run: curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin

      - name: Generate code coverage
        run: cargo +nightly llvm-cov --all-features --workspace --lcov --output-path lcov.info --ignore-filename-regex mock

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: lcov.info
          fail_ci_if_error: true

      - name: fmt check
        run: cargo +nightly fmt --all -- --check

      - name: Clippy check
        run: cargo +nightly clippy --all-features -- -D warnings

      - name: Cargo test
        run: cargo +nightly test
